---
- include: tasks/set_repos.yml

- name: update package lists
  apt: 
    update_cache: yes

- name: write APT config file
  copy:
    src: files/_etc_apt_apt.conf.d_99mindeps
    dest: /etc/apt/apt.conf.d/99mindeps

- name: check for initial_purge_happened flag
  stat: path=flags/initial_purge_happened
  register: initial_purge

- name: perform initial purge
  include: tasks/initial_purge.yml
  when: initial_purge.stat.exists == False

- name: APT - dist-upgrade
  apt:
    upgrade: dist
