---
- name: write terminal config file
  copy:
    src: files/_etc_default_console-setup
    dest: /etc/default/console-setup

- name: write keyboard config file
  copy:
    src: files/_etc_default_keyboard
    dest: /etc/default/keyboard

- name: ensure locales is installed
  apt:
     name: locales 
     state: present

- name: ensure setupcon is installed
  apt:
     name: console-setup
     state: present

- name: generate en_US.UTF-8 locale
  locale_gen:
    name: en_US.UTF-8
    state: present

- name: write /etc/profile (with locale export) 
  copy:
    src: files/_etc_profile
    dest: /etc/profile

- name: run setupcon to apply console settings from /etc/default/
  command: setupcon
