---

- name: APT - use stretch repo 
  apt_repository:
    repo: deb http://ftp.debian.org/debian/ stretch main contrib non-free
    state: present

- name: APT - use stretch security updates repo
  apt_repository:
    repo: deb http://security.debian.org/ stretch/updates main contrib non-free
    state: present

- name: APT - use stretch-updates repo
  apt_repository:
    repo: deb http://ftp.debian.org/debian/ stretch-updates main contrib non-free
    state: present

- name: APT - use stretch-backports repo
  apt_repository:
    repo: deb http://ftp.debian.org/debian stretch-backports main contrib non-free
    state: present
