---
- hosts: all
  user: root
  become: yes
  tasks:

  - name: symlink system files
    file: state=link force=yes src={{item}} dest={{item|basename|regex_replace('___','/')}}
    with_fileglob: ~/config/ansible/files/*
  - name: set hostname for current session
    shell: hostname w530

  # Configure package management.
  - name: update package lists
    apt: update_cache=yes
  - name: check for initial_purge_happened flag
    stat: path=flags/initial_purge_happened
    register: initial_purge
  - name: perform initial purge
    include: tasks/initial_purge.yml
    when: initial_purge.stat.exists == False
  - name: APT - dist-upgrade
    apt: upgrade=dist

  # Configure console.
  - name: ensure locales and console-setup are installed
    apt: name={{item}} state=present
    with_items:
    - locales
    - console-setup
  - name: generate en_US.UTF-8 locale
    locale_gen: name=en_US.UTF-8 state=present
  - name: run setupcon to apply console settings from /etc/default/
    command: setupcon

  # Miscellaneous.
  - name: Ensure dotfile symlinks
    file: state=link force=yes src={{item}} dest=~/.{{item|basename}}
    with_fileglob: ~/config/ansible/dotfiles/*
  - name: ensure man-db, manpages is installed
    apt: name={{item}} state=present
    with_items:
    - man-db
    - manpages
  - name: set /etc/localtime
    file: state=link force=yes src=/usr/share/zoneinfo/Europe/Berlin dest=/etc/localtime
  - name: ensure git, vim, less are installed
    apt: name={{item}} state=present
    with_items:
    - git
    - vim
    - less
  - name: create user plom
    user: name=plom
  - name: ensure boot messages are not cleared on start up
    replace: dest=/etc/systemd/system/getty.target.wants/getty@tty1.service regexp='^TTYVTDisallocate=yes.*$' replace='TTYVDisallocate=no'
