---
- hosts: all
  user: root
  become: yes
  tasks:

  - name: symlink system files
    file: state=hard force=yes src={{item}} dest={{item|basename|regex_replace('___','/')}}
    with_fileglob: ~/config/ansible/files/system/*
  - name: set hostname for current session
    shell: hostname w530

  # Configure package management.
  - name: update package lists
    apt: update_cache=yes
  - name: check for initial_purge_happened flag
    stat: path=flags/initial_purge_happened
    register: initial_purge
  - name: perform initial purge
    include: tasks/initial_purge.yml
    when: initial_purge.stat.exists == False
  - name: APT - dist-upgrade
    apt: upgrade=dist

  # Configure console.
  - name: symlink console config files
    file: state=link force=yes src={{item}} dest={{item|basename|regex_replace('___','/')}}
    with_fileglob: ~/config/ansible/files/console/*
  - name: ensure locales and console-setup are installed
    apt: name={{item}} state=present
    with_items:
    - locales
    - console-setup
  - name: generate en_US.UTF-8 locale
    locale_gen: name=en_US.UTF-8 state=present
  - name: run setupcon to apply console settings from /etc/default/
    command: setupcon

  # Miscellaneous.
  - name: Ensure dotfile symlinks
    file: state=link force=yes src={{item}} dest=~/.{{item|basename}}
    with_fileglob:
    - ~/config/dotfiles/minimal/*
    - ~/config/dotfiles/root/*
  - name: ensure ~/.vimbackups directory
    file: state=directory dest=~/.vimbackups
  - name: ensure man-db, manpages is installed
    apt: name={{item}} state=present
    with_items:
    - man-db
    - manpages
  - name: set /etc/localtime
    file: state=link force=yes src=/usr/share/zoneinfo/Europe/Berlin dest=/etc/localtime
  - name: ensure sudo, git, vim, less, openssh are installed
    apt: name={{item}} state=present
    with_items:
    - git
    - vim
    - less
    - sudo
    - openssh-client
  - name: ensure boot messages are not cleared on start up
    replace: dest=/etc/systemd/system/getty.target.wants/getty@tty1.service regexp='^TTYVTDisallocate=yes.*$' replace='TTYVTDisallocate=no'

  # Config user.
  - name: create user plom with sudo privileges and bash shell
    user: name=plom groups=sudo shell=/bin/bash
  - name: have config repo in user directory
    git: repo=https://github.com/plomlompom/config dest=/home/plom/config
    become_user: plom
    become_method: su

  # Ensure X window environment.
  - name: ensure minimal X window environment
    apt: name={{item}} state=present
    with_items:
    - xserver-xorg-core
    - xserver-xorg-input-evdev  # supports lal input devices the kernel knows about
    - xinit  # contains startx
    - libpam-systemd  # needed to start X as non-root
  - name: ensure basic X tools
    apt: name={{item}} state=present
    with_items:
    - xterm
    - x11-xserver-utils  # includes xrdb which applies .Xresources files
    - redshift 
    - i3
    - i3status
    - dmenu

  # Set up pentadactyl.
  - name: ensure browser environment
    apt: name={{item}} state=present
    with_items:
    - iceweasel
    - xul-ext-noscript
    - xul-ext-pentadactyl
    - vim-gtk  # used by pentadactyl for text editing
