- hosts: all
  tasks:

  - name: ensure ~/.vimbackups directory
    file: state=directory dest=~/.vimbackups
  - name: Ensure dotfile symlinks
    file: state=link force=yes src={{item}} dest=~/.{{item|basename}}
    with_fileglob:
    - ~/config/dotfiles/minimal/*
    - ~/config/dotfiles/user/thinkpad/minimal/*
    - ~/config/dotfiles/user/thinkpad/{{ system_name }}/*
  - name: ensure ~/downloads directory
    file: state=directory dest=~/downloads
