- hosts: all
  tasks:

  - name: ensure ~/.vimbackups directory
    file: state=directory dest=~/.vimbackups
  - name: Ensure dotfile symlinks
    file: state=link force=yes src={{item}} dest=~/.{{item|basename}}
    - ~/configdotfiles/minimal/*
    - ~/configdotfiles/user/minimal/*
    - ~/configdotfiles/user/thinkpad/minimal/*
